const ExcelJS = require('exceljs');

const PALETTE = {
  headerBg: '1E293B',       // Slate dark navy
  headerText: 'FFFFFF',     // White
  accentGold: 'D4AF37',     // Gold primary
  goldText: '92400E',       // Dark gold/amber text
  zebraRow: 'F8FAFC',       // Very light slate
  white: 'FFFFFF',
  borderLight: 'E2E8F0',    // Light slate border
  borderMedium: '94A3B8',   // Medium slate border
  totalBg: 'F1F5F9',        // Slate-100 for totals
  textDark: '0F172A',       // Slate-900
  textMuted: '64748B',      // Slate-500
  greenText: '059669',      // Emerald
  redText: 'DC2626',        // Red
};

const FORMATS = {
  currency: '"₱"#,##0.00',
  integer: '#,##0',
  percent: '0.0%',
  date: 'yyyy-mm-dd hh:mm',
};

function formatCurrency(val) {
  const n = Number(val);
  return Number.isFinite(n) ? n : 0;
}

function formatInteger(val) {
  const n = Math.round(Number(val));
  return Number.isFinite(n) ? n : 0;
}

function formatDate(val) {
  if (!val) return '';
  const d = new Date(val);
  return isNaN(d.getTime()) ? String(val) : d;
}

/**
 * Applies standard cell borders
 */
function setCellBorder(cell, { top = 'thin', bottom = 'thin', left = 'thin', right = 'thin', color = PALETTE.borderLight } = {}) {
  cell.border = {
    top: top ? { style: top, color: { argb: color } } : undefined,
    bottom: bottom ? { style: bottom, color: { argb: color } } : undefined,
    left: left ? { style: left, color: { argb: color } } : undefined,
    right: right ? { style: right, color: { argb: color } } : undefined,
  };
}

/**
 * Generates an Excel workbook buffer using ExcelJS matching the active report and filters.
 */
async function generateReportWorkbook(reportData = {}, options = {}) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'CosmosCraft Business Intelligence';
  workbook.lastModifiedBy = options.printedBy || 'CosmosCraft Admin';
  workbook.created = new Date();
  workbook.modified = new Date();

  const reportType = (reportData.reportType || options.reportType || 'all').toLowerCase();
  const dateLabel = options.dateLabel || 'All Time';
  const printedBy = options.printedBy || 'Administrator';
  const datePrinted = options.datePrinted || new Date().toLocaleString('en-PH');
  const activeFilters = options.activeFilters || {};

  const summary = reportData.summary || {
    grossSales: reportData.grossSales || 0,
    totalAdjustments: reportData.totalAdjustments || 0,
    netSales: reportData.netSales || 0,
    totalTransactions: reportData.totalTransactions || 0,
    averagePerTransaction: reportData.averagePerTransaction || 0,
  };

  const transactions = reportData.transactions || [];

  // Sheet Title
  const typeTitles = {
    all: 'All Sales & Transactions',
    online: 'Online Sales Report',
    pos: 'Walk-in POS Sales Report',
    customization: 'Customization Projects Report',
    appointments: 'Appointments & Service Bookings Report',
    refunds: 'Refunds & Adjustments Report',
  };
  const sheetTitle = typeTitles[reportType] || 'Sales Report';
  const cleanSheetName = sheetTitle.replace(/[*?:\\/\[\]]/g, ' ').trim().substring(0, 31);

  const ws = workbook.addWorksheet(cleanSheetName, {
    pageSetup: {
      orientation: 'landscape',
      paperSize: 9, // A4
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
    },
    views: [{ state: 'frozen', ySplit: 13, xSplit: 0 }],
  });

  // 1. Header Banner
  ws.mergeCells('A1:I1');
  const titleCell = ws.getCell('A1');
  titleCell.value = 'COSMOSCRAFT GUITARS & CUSTOM SHOP';
  titleCell.font = { name: 'Segoe UI', size: 16, bold: true, color: { argb: PALETTE.headerBg } };
  titleCell.alignment = { horizontal: 'left', vertical: 'middle' };
  ws.getRow(1).height = 28;

  ws.mergeCells('A2:I2');
  const subtitleCell = ws.getCell('A2');
  subtitleCell.value = `Official Business Report: ${sheetTitle.toUpperCase()}`;
  subtitleCell.font = { name: 'Segoe UI', size: 12, bold: true, color: { argb: PALETTE.goldText } };
  subtitleCell.alignment = { horizontal: 'left', vertical: 'middle' };
  ws.getRow(2).height = 20;

  // 2. Metadata Block (Rows 4-6)
  const filterSummary = Object.entries(activeFilters)
    .filter(([_, v]) => v && v !== 'all' && v !== '')
    .map(([k, v]) => `${k.replace('_', ' ').toUpperCase()}: ${v}`)
    .join('  |  ') || 'None (All matching records)';

  const metaRows = [
    { label1: 'Reporting Period:', val1: dateLabel, label2: 'Date Generated:', val2: datePrinted },
    { label1: 'Generated By:', val1: printedBy, label2: 'Active Filters:', val2: filterSummary },
    { label1: 'Report Category:', val1: sheetTitle, label2: 'Currency:', val2: 'Philippine Peso (PHP / ₱)' },
  ];

  metaRows.forEach((item, idx) => {
    const rowNum = 4 + idx;
    const r = ws.getRow(rowNum);
    r.height = 18;

    ws.getCell(`A${rowNum}`).value = item.label1;
    ws.getCell(`A${rowNum}`).font = { name: 'Segoe UI', size: 9, bold: true, color: { argb: PALETTE.textMuted } };
    ws.getCell(`B${rowNum}`).value = item.val1;
    ws.getCell(`B${rowNum}`).font = { name: 'Segoe UI', size: 9, bold: true, color: { argb: PALETTE.textDark } };

    ws.getCell(`E${rowNum}`).value = item.label2;
    ws.getCell(`E${rowNum}`).font = { name: 'Segoe UI', size: 9, bold: true, color: { argb: PALETTE.textMuted } };
    ws.getCell(`F${rowNum}`).value = item.val2;
    ws.getCell(`F${rowNum}`).font = { name: 'Segoe UI', size: 9, bold: false, color: { argb: PALETTE.textDark } };
  });

  // 3. Key Performance Indicators (KPIs) Summary Block (Rows 8-10)
  ws.mergeCells('A8:I8');
  const kpiHeader = ws.getCell('A8');
  kpiHeader.value = 'KEY PERFORMANCE INDICATORS (KPIs)';
  kpiHeader.font = { name: 'Segoe UI', size: 10, bold: true, color: { argb: PALETTE.textMuted } };
  ws.getRow(8).height = 18;

  const kpis = [
    { col: 'A', endCol: 'B', label: 'GROSS SALES', value: formatCurrency(summary.grossSales), isCurrency: true },
    { col: 'C', endCol: 'D', label: 'TOTAL ADJUSTMENTS', value: formatCurrency(summary.totalAdjustments), isCurrency: true, isRed: summary.totalAdjustments > 0 },
    { col: 'E', endCol: 'F', label: 'NET SALES', value: formatCurrency(summary.netSales), isCurrency: true, isGold: true },
    { col: 'G', endCol: 'G', label: 'TRANSACTIONS', value: formatInteger(summary.totalTransactions), isCurrency: false },
    { col: 'H', endCol: 'I', label: 'AVG TRANSACTION', value: formatCurrency(summary.averagePerTransaction), isCurrency: true },
  ];

  kpis.forEach((kpi) => {
    if (kpi.col !== kpi.endCol) {
      ws.mergeCells(`${kpi.col}9:${kpi.endCol}9`);
      ws.mergeCells(`${kpi.col}10:${kpi.endCol}10`);
    }

    const lblCell = ws.getCell(`${kpi.col}9`);
    lblCell.value = kpi.label;
    lblCell.font = { name: 'Segoe UI', size: 8, bold: true, color: { argb: PALETTE.textMuted } };
    lblCell.alignment = { horizontal: 'center', vertical: 'middle' };
    lblCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'F1F5F9' } };
    setCellBorder(lblCell, { top: 'thin', bottom: 'thin', left: 'thin', right: 'thin', color: PALETTE.borderLight });

    const valCell = ws.getCell(`${kpi.col}10`);
    valCell.value = kpi.value;
    valCell.font = {
      name: 'Segoe UI',
      size: 11,
      bold: true,
      color: { argb: kpi.isRed ? PALETTE.redText : kpi.isGold ? PALETTE.goldText : PALETTE.textDark },
    };
    valCell.alignment = { horizontal: 'center', vertical: 'middle' };
    valCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: kpi.isGold ? 'FEF3C7' : 'FFFFFF' } };
    if (kpi.isCurrency) valCell.numFmt = FORMATS.currency;
    else valCell.numFmt = FORMATS.integer;
    setCellBorder(valCell, { top: 'thin', bottom: 'thin', left: 'thin', right: 'thin', color: PALETTE.borderMedium });
  });
  ws.getRow(9).height = 16;
  ws.getRow(10).height = 24;

  // 4. Itemized Transactions Table Header (Row 13)
  const columnsByReport = {
    all: [
      { key: 'transaction_number', header: 'Transaction #', width: 22, align: 'left' },
      { key: 'date', header: 'Date & Time', width: 19, align: 'center', format: FORMATS.date },
      { key: 'channel', header: 'Sales Channel', width: 16, align: 'center' },
      { key: 'customer_name', header: 'Customer', width: 24, align: 'left' },
      { key: 'payment_method', header: 'Payment Method', width: 16, align: 'center' },
      { key: 'status', header: 'Status', width: 14, align: 'center' },
      { key: 'gross_amount', header: 'Gross Amount', width: 18, align: 'right', format: FORMATS.currency, isTotal: true },
      { key: 'adjustment_amount', header: 'Adjustments', width: 16, align: 'right', format: FORMATS.currency, isTotal: true },
      { key: 'net_amount', header: 'Net Amount', width: 18, align: 'right', format: FORMATS.currency, isTotal: true },
    ],
    online: [
      { key: 'transaction_number', header: 'Order Number', width: 22, align: 'left' },
      { key: 'date', header: 'Order Date', width: 19, align: 'center', format: FORMATS.date },
      { key: 'customer_name', header: 'Customer Name', width: 24, align: 'left' },
      { key: 'status', header: 'Order Status', width: 16, align: 'center' },
      { key: 'payment_status', header: 'Payment Status', width: 16, align: 'center' },
      { key: 'payment_method', header: 'Payment Method', width: 16, align: 'center' },
      { key: 'subtotal', header: 'Subtotal', width: 16, align: 'right', format: FORMATS.currency, isTotal: true },
      { key: 'shipping_cost', header: 'Shipping', width: 14, align: 'right', format: FORMATS.currency, isTotal: true },
      { key: 'gross_amount', header: 'Total Amount', width: 18, align: 'right', format: FORMATS.currency, isTotal: true },
    ],
    pos: [
      { key: 'transaction_number', header: 'Receipt / Sale #', width: 22, align: 'left' },
      { key: 'date', header: 'Date & Time', width: 19, align: 'center', format: FORMATS.date },
      { key: 'staff_name', header: 'Cashier / Staff', width: 20, align: 'left' },
      { key: 'customer_name', header: 'Customer Name', width: 22, align: 'left' },
      { key: 'payment_method', header: 'Payment Method', width: 16, align: 'center' },
      { key: 'status', header: 'Sale Status', width: 15, align: 'center' },
      { key: 'subtotal', header: 'Subtotal', width: 16, align: 'right', format: FORMATS.currency, isTotal: true },
      { key: 'discount_amount', header: 'Discount', width: 14, align: 'right', format: FORMATS.currency, isTotal: true },
      { key: 'gross_amount', header: 'Total Collected', width: 18, align: 'right', format: FORMATS.currency, isTotal: true },
    ],
    customization: [
      { key: 'transaction_number', header: 'Project / Order #', width: 22, align: 'left' },
      { key: 'date', header: 'Order Date', width: 19, align: 'center', format: FORMATS.date },
      { key: 'customer_name', header: 'Customer Name', width: 24, align: 'left' },
      { key: 'status', header: 'Project Status', width: 16, align: 'center' },
      { key: 'payment_status', header: 'Payment Status', width: 16, align: 'center' },
      { key: 'payment_method', header: 'Payment Method', width: 16, align: 'center' },
      { key: 'gross_amount', header: 'Total Project Value', width: 20, align: 'right', format: FORMATS.currency, isTotal: true },
      { key: 'adjustment_amount', header: 'Adjustments', width: 16, align: 'right', format: FORMATS.currency, isTotal: true },
      { key: 'net_amount', header: 'Net Revenue', width: 18, align: 'right', format: FORMATS.currency, isTotal: true },
    ],
    appointments: [
      { key: 'transaction_number', header: 'Reference #', width: 22, align: 'left' },
      { key: 'date', header: 'Scheduled Date', width: 19, align: 'center', format: FORMATS.date },
      { key: 'customer_name', header: 'Customer Name', width: 24, align: 'left' },
      { key: 'service_names', header: 'Services', width: 30, align: 'left' },
      { key: 'status', header: 'Appointment Status', width: 18, align: 'center' },
      { key: 'payment_status', header: 'Payment Status', width: 16, align: 'center' },
      { key: 'payment_method', header: 'Payment Method', width: 16, align: 'center' },
      { key: 'gross_amount', header: 'Service Fee', width: 18, align: 'right', format: FORMATS.currency, isTotal: true },
    ],
    refunds: [
      { key: 'transaction_number', header: 'Request / Ref #', width: 20, align: 'left' },
      { key: 'date', header: 'Date Requested', width: 19, align: 'center', format: FORMATS.date },
      { key: 'channel', header: 'Source Channel', width: 16, align: 'center' },
      { key: 'related_number', header: 'Related Order / Sale', width: 20, align: 'left' },
      { key: 'customer_name', header: 'Customer', width: 22, align: 'left' },
      { key: 'adjustment_type', header: 'Adjustment Type', width: 18, align: 'center' },
      { key: 'status', header: 'Status', width: 15, align: 'center' },
      { key: 'gross_amount', header: 'Amount Requested', width: 18, align: 'right', format: FORMATS.currency, isTotal: true },
      { key: 'adjustment_amount', header: 'Approved / Refunded', width: 18, align: 'right', format: FORMATS.currency, isTotal: true },
    ],
  };

  const columns = columnsByReport[reportType] || columnsByReport.all;

  // Set explicit column widths
  columns.forEach((col, idx) => {
    ws.getColumn(idx + 1).width = col.width;
  });

  const headerRowNum = 13;
  const headerRow = ws.getRow(headerRowNum);
  headerRow.height = 24;

  columns.forEach((col, idx) => {
    const cell = headerRow.getCell(idx + 1);
    cell.value = col.header;
    cell.font = { name: 'Segoe UI', size: 10, bold: true, color: { argb: PALETTE.headerText } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.headerBg } };
    cell.alignment = { horizontal: col.align, vertical: 'middle' };
    setCellBorder(cell, { top: 'medium', bottom: 'medium', left: 'thin', right: 'thin', color: PALETTE.borderLight });
  });

  // 5. Data Rows
  let currentRow = 14;
  if (transactions.length === 0) {
    ws.mergeCells(`A14:${String.fromCharCode(65 + columns.length - 1)}14`);
    const emptyCell = ws.getCell('A14');
    emptyCell.value = 'No transactions recorded for the selected period and filter criteria.';
    emptyCell.font = { name: 'Segoe UI', size: 10, italic: true, color: { argb: PALETTE.textMuted } };
    emptyCell.alignment = { horizontal: 'center', vertical: 'middle' };
    ws.getRow(14).height = 30;
    currentRow = 15;
  } else {
    transactions.forEach((tx, rIdx) => {
      const row = ws.getRow(currentRow);
      row.height = 20;
      const isZebra = rIdx % 2 === 1;

      columns.forEach((col, cIdx) => {
        const cell = row.getCell(cIdx + 1);
        let val = tx[col.key];

        if (col.format === FORMATS.date) {
          val = formatDate(val);
        } else if (col.format === FORMATS.currency) {
          val = formatCurrency(val);
        }

        cell.value = val !== undefined && val !== null ? val : '';
        cell.font = { name: 'Segoe UI', size: 9, color: { argb: PALETTE.textDark } };
        cell.alignment = { horizontal: col.align, vertical: 'middle' };
        if (col.format) cell.numFmt = col.format;

        if (isZebra) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.zebraRow } };
        }
        setCellBorder(cell, { top: 'thin', bottom: 'thin', left: 'thin', right: 'thin', color: PALETTE.borderLight });
      });

      currentRow++;
    });

    // 6. Total Summary Row
    const totalRow = ws.getRow(currentRow);
    totalRow.height = 24;

    columns.forEach((col, cIdx) => {
      const cell = totalRow.getCell(cIdx + 1);
      const colLetter = String.fromCharCode(65 + cIdx);

      if (cIdx === 0) {
        cell.value = 'TOTAL';
        cell.font = { name: 'Segoe UI', size: 10, bold: true, color: { argb: PALETTE.textDark } };
        cell.alignment = { horizontal: 'left', vertical: 'middle' };
      } else if (col.isTotal) {
        cell.value = {
          formula: `SUM(${colLetter}14:${colLetter}${currentRow - 1})`,
          result: formatCurrency(transactions.reduce((acc, t) => acc + (Number(t[col.key]) || 0), 0)),
        };
        cell.font = { name: 'Segoe UI', size: 10, bold: true, color: { argb: PALETTE.textDark } };
        cell.alignment = { horizontal: 'right', vertical: 'middle' };
        cell.numFmt = FORMATS.currency;
      } else {
        cell.value = '';
      }

      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.totalBg } };
      setCellBorder(cell, { top: 'medium', bottom: 'double', left: 'thin', right: 'thin', color: PALETTE.borderMedium });
    });

    // Enable AutoFilter on table headers
    ws.autoFilter = {
      from: { row: headerRowNum, column: 1 },
      to: { row: currentRow, column: columns.length },
    };
  }

  // 7. Add Breakdown Sheet if "all"
  if (reportType === 'all' && reportData.channels) {
    const chSheet = workbook.addWorksheet('Channel Breakdown', {
      views: [{ state: 'frozen', ySplit: 5, xSplit: 0 }],
    });

    chSheet.mergeCells('A1:F1');
    chSheet.getCell('A1').value = 'COSMOSCRAFT SALES BY CHANNEL';
    chSheet.getCell('A1').font = { name: 'Segoe UI', size: 14, bold: true, color: { argb: PALETTE.headerBg } };
    chSheet.getRow(1).height = 24;

    const chHeaders = ['Sales Channel', 'Transactions', 'Gross Sales', 'Adjustments', 'Net Sales', '% of Net'];
    const chWidths = [24, 16, 18, 18, 18, 14];
    chWidths.forEach((w, i) => { chSheet.getColumn(i + 1).width = w; });

    const chHeaderRow = chSheet.getRow(4);
    chHeaderRow.height = 22;
    chHeaders.forEach((h, i) => {
      const cell = chHeaderRow.getCell(i + 1);
      cell.value = h;
      cell.font = { name: 'Segoe UI', size: 10, bold: true, color: { argb: PALETTE.headerText } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.headerBg } };
      cell.alignment = { horizontal: i === 0 ? 'left' : 'right', vertical: 'middle' };
      setCellBorder(cell, { top: 'medium', bottom: 'medium', left: 'thin', right: 'thin', color: PALETTE.borderLight });
    });

    const chList = [
      { name: 'Online Orders', key: 'online' },
      { name: 'Walk-in / POS', key: 'walkIn' },
      { name: 'Customization / Projects', key: 'customization' },
      { name: 'Appointments', key: 'appointments' },
    ];

    let chRowIdx = 5;
    const netTotal = summary.netSales || 1;

    chList.forEach((c) => {
      const d = (reportData.channels && (reportData.channels[c.key] || reportData.channels[c.name.toLowerCase()])) || { gross: 0, adjustments: 0, net: 0, transactions: 0 };
      const r = chSheet.getRow(chRowIdx);
      r.height = 20;

      r.getCell(1).value = c.name;
      r.getCell(1).font = { name: 'Segoe UI', size: 9, bold: true, color: { argb: PALETTE.textDark } };
      setCellBorder(r.getCell(1));

      r.getCell(2).value = formatInteger(d.transactions);
      r.getCell(2).numFmt = FORMATS.integer;
      r.getCell(2).alignment = { horizontal: 'right' };
      setCellBorder(r.getCell(2));

      r.getCell(3).value = formatCurrency(d.gross);
      r.getCell(3).numFmt = FORMATS.currency;
      r.getCell(3).alignment = { horizontal: 'right' };
      setCellBorder(r.getCell(3));

      r.getCell(4).value = formatCurrency(d.adjustments);
      r.getCell(4).numFmt = FORMATS.currency;
      r.getCell(4).alignment = { horizontal: 'right' };
      setCellBorder(r.getCell(4));

      r.getCell(5).value = formatCurrency(d.net);
      r.getCell(5).numFmt = FORMATS.currency;
      r.getCell(5).font = { bold: true };
      r.getCell(5).alignment = { horizontal: 'right' };
      setCellBorder(r.getCell(5));

      const share = netTotal > 0 ? (d.net / netTotal) : 0;
      r.getCell(6).value = Number(share.toFixed(4));
      r.getCell(6).numFmt = FORMATS.percent;
      r.getCell(6).alignment = { horizontal: 'right' };
      setCellBorder(r.getCell(6));

      chRowIdx++;
    });

    // Total row for channel sheet
    const chTotalRow = chSheet.getRow(chRowIdx);
    chTotalRow.height = 22;
    chTotalRow.getCell(1).value = 'TOTAL';
    chTotalRow.getCell(1).font = { name: 'Segoe UI', size: 9, bold: true };
    chTotalRow.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.totalBg } };
    setCellBorder(chTotalRow.getCell(1), { top: 'medium', bottom: 'double' });

    chTotalRow.getCell(2).value = { formula: `SUM(B5:B${chRowIdx - 1})`, result: formatInteger(summary.totalTransactions) };
    chTotalRow.getCell(2).numFmt = FORMATS.integer;
    chTotalRow.getCell(2).font = { bold: true };
    chTotalRow.getCell(2).alignment = { horizontal: 'right' };
    chTotalRow.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.totalBg } };
    setCellBorder(chTotalRow.getCell(2), { top: 'medium', bottom: 'double' });

    chTotalRow.getCell(3).value = { formula: `SUM(C5:C${chRowIdx - 1})`, result: formatCurrency(summary.grossSales) };
    chTotalRow.getCell(3).numFmt = FORMATS.currency;
    chTotalRow.getCell(3).font = { bold: true };
    chTotalRow.getCell(3).alignment = { horizontal: 'right' };
    chTotalRow.getCell(3).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.totalBg } };
    setCellBorder(chTotalRow.getCell(3), { top: 'medium', bottom: 'double' });

    chTotalRow.getCell(4).value = { formula: `SUM(D5:D${chRowIdx - 1})`, result: formatCurrency(summary.totalAdjustments) };
    chTotalRow.getCell(4).numFmt = FORMATS.currency;
    chTotalRow.getCell(4).font = { bold: true };
    chTotalRow.getCell(4).alignment = { horizontal: 'right' };
    chTotalRow.getCell(4).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.totalBg } };
    setCellBorder(chTotalRow.getCell(4), { top: 'medium', bottom: 'double' });

    chTotalRow.getCell(5).value = { formula: `SUM(E5:E${chRowIdx - 1})`, result: formatCurrency(summary.netSales) };
    chTotalRow.getCell(5).numFmt = FORMATS.currency;
    chTotalRow.getCell(5).font = { bold: true };
    chTotalRow.getCell(5).alignment = { horizontal: 'right' };
    chTotalRow.getCell(5).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.totalBg } };
    setCellBorder(chTotalRow.getCell(5), { top: 'medium', bottom: 'double' });

    chTotalRow.getCell(6).value = 1.0;
    chTotalRow.getCell(6).numFmt = FORMATS.percent;
    chTotalRow.getCell(6).font = { bold: true };
    chTotalRow.getCell(6).alignment = { horizontal: 'right' };
    chTotalRow.getCell(6).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.totalBg } };
    setCellBorder(chTotalRow.getCell(6), { top: 'medium', bottom: 'double' });
  }

  return workbook.xlsx.writeBuffer();
}

/**
 * Backwards compatibility helper for customer summary
 */
async function generateCustomerSummaryExcelWorkbook(customerSummary = {}, options = {}) {
  const workbook = new ExcelJS.Workbook();
  const ws = workbook.addWorksheet('Customer Summary');
  const rows = customerSummary.rows || [];

  ws.columns = [
    { header: 'Channel', key: 'channel', width: 18 },
    { header: 'Customer Name', key: 'customer_name', width: 26 },
    { header: 'Transactions', key: 'transactions', width: 14 },
    { header: 'Total Sales', key: 'total_sales', width: 18 },
    { header: 'Last Purchase Date', key: 'last_purchase_date', width: 18 },
  ];

  const headerRow = ws.getRow(1);
  headerRow.font = { bold: true, color: { argb: PALETTE.headerText } };
  headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PALETTE.headerBg } };

  rows.forEach((r) => {
    ws.addRow({
      channel: r.channel,
      customer_name: r.customer_name,
      transactions: formatInteger(r.transactions),
      total_sales: formatCurrency(r.total_sales),
      last_purchase_date: r.last_purchase_date ? new Date(r.last_purchase_date).toLocaleDateString() : 'N/A',
    });
  });

  return workbook.xlsx.writeBuffer();
}

/**
 * Backward compatibility wrapper
 */
async function generateSalesExcelWorkbook(salesReport = {}, options = {}) {
  return generateReportWorkbook(salesReport, options);
}

module.exports = {
  generateReportWorkbook,
  generateSalesExcelWorkbook,
  generateCustomerSummaryExcelWorkbook,
};
